org: revesh
app: backend
service: pricing-services

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    COIN_GECKO_API_KEY: ${env:COIN_GECKO_API_KEY}
    RABBITMQ_URL: ${env:RABBITMQ_URL}
    MAILERSEND_API_KEY: ${env:MAILERSEND_API_KEY}
    MAILERSEND_FROM_EMAIL: ${env:MAILERSEND_FROM_EMAIL}
    MAILERSEND_FROM_NAME: ${env:MAILERSEND_FROM_NAME}

functions:
  api:
    handler: build/index.handler #
    events:
      - httpApi: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
