org: revesh
app: backend
service: search-history-service

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: "production"
    RABBITMQ_URL: "amqps://xkmqzjmf:d_24KbOUGwUPMeic9ynr2vADkmQmB8U7@rattlesnake.rmq.cloudamqp.com/xkmqzjmf"
    DB_HOST: "ep-frosty-bonus-a5720ndt.us-east-2.aws.neon.tech"
    DB_PORT: 5432
    DB_USERNAME: "nimo-industries_owner"
    DB_PASSWORD: "z7sfRx3OMWkD"
    DB_NAME: "nimo-industries"
    DB_SSLMODE: true

functions:
  api:
    handler: build/index.handler #
    timeout: 10 # Set the timeout value in seconds
    events:
      - httpApi: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
